"use strict";
const $=s=>document.querySelector(s), app=$('#app');
const prices=[61200,61600,61120,62200,62900,62600,63500,63100,64200,65000,64700,65400,66100,65800,66900,67540];
let screen='terminal', range='1H';
function money(n){return '$'+Math.round(n).toLocaleString('en-US')}
function chart(){const c=document.querySelector('#priceChart');if(!c)return;const r=c.getBoundingClientRect(),d=devicePixelRatio||1;c.width=r.width*d;c.height=r.height*d;const x=c.getContext('2d');x.scale(d,d);const w=r.width,h=r.height,min=Math.min(...prices)-900,max=Math.max(...prices)+500;x.strokeStyle='#7897ff';x.lineWidth=2.5;x.shadowColor='#7897ff';x.shadowBlur=9;x.beginPath();prices.forEach((p,i)=>{const px=i/(prices.length-1)*w,py=h-(p-min)/(max-min)*h*.82-10;i?x.lineTo(px,py):x.moveTo(px,py)});x.stroke();x.shadowBlur=0;x.lineTo(w,h);x.lineTo(0,h);x.closePath();const g=x.createLinearGradient(0,0,0,h);g.addColorStop(0,'#7897ff35');g.addColorStop(1,'#7897ff00');x.fillStyle=g;x.fill();x.strokeStyle='#2a3850';x.lineWidth=1;for(let i=1;i<5;i++){x.beginPath();x.moveTo(0,h*i/5);x.lineTo(w,h*i/5);x.stroke()}}
function header(title,sub='Сегодня, 08:42 UTC'){return `<div class="title-row"><div><div class="eyebrow">операционный центр · сезон 01</div><h1>${title}</h1><p>${sub}</p></div><div class="date">● LIVE / PAPER MODE</div></div>`}
function terminal(){return `${header('Доброе утро, Алексей','Твой капитал работает в безопасном режиме — без реальных денег.')}
<div class="grid"><section class="card chart-card"><h3>BTC / USD <span>BINANCE · PERPETUAL</span></h3><div><span class="price">$67,540.00</span><span class="change up">+2.84%</span></div><div class="chart"><canvas id="priceChart"></canvas></div><div class="chart-labels"><span>06:00</span><span>06:15</span><span>06:30</span><span>06:45</span><span>07:00</span></div><div class="range">${['15M','1H','4H','1D'].map(x=>`<button class="${range===x?'active':''}" data-range="${x}">${x}</button>`).join('')}</div></section>
<section class="card"><h3>Мой баланс <span>USD</span></h3><div class="portfolio-value">$12,480<span class="up" style="font:13px 'DM Mono'"> +4.2%</span></div><div class="stat"><span>Доступно</span><b>$8,920.00</b></div><div class="stat"><span>В позиции</span><b>$3,560.00</b></div><button class="btn ghost" style="width:100%;margin-top:7px" data-action="portfolio">Открыть портфель →</button></section>
<section class="card"><h3>Настроение рынка <span>из 100</span></h3><div style="font-size:31px;font-weight:600">68 <span class="up" style="font-size:13px"> жадность</span></div><div class="sentiment"><i></i></div><div class="sentiment-label"><span>страх</span><span>нейтрально</span><span>жадность</span></div><div class="stat" style="margin-top:24px"><span>BTC dominance</span><b>52.4%</b></div></section>
<section class="card mission"><h3>Активная миссия <span class="pill">+240 XP</span></h3><div class="mission-row"><div class="mission-icon">♢</div><div><b>Поймай импульс</b><small>Открой LONG после подтверждения пробоя</small><div class="progress"><i style="width:62%"></i></div></div><span class="reward">62%</span></div><div class="action-row"><button class="btn" data-screen="learn">Продолжить урок</button><button class="btn ghost" data-action="trade">Открыть терминал</button></div></section>
</div>`}
function learn(){return `${header('Тренировочный зал','Развивай навык, а не азарт. Каждое решение объясняется.') }<div class="screen-grid"><section class="card hero-card"><div class="eyebrow">урок 03 · риск-менеджмент</div><h2 style="font-size:27px;margin:12px 0 6px">Цена не обязана быть правой,<br>чтобы твой план был правильным.</h2><p style="color:var(--muted);line-height:1.6">Научись выставлять стоп-лосс до входа в сделку. Пройди короткий сценарий и получи XP.</p><button class="btn" data-action="lesson">Запустить сценарий →</button></section><section class="card"><h3>Прогресс курса</h3><div class="portfolio-value" style="font-size:32px">42%</div><div class="progress"><i style="width:42%"></i></div><div class="stat"><span>7 из 16 уроков</span><b>1 280 XP</b></div></section><section style="grid-column:span 3"><div class="learning-list"><div class="lesson"><span class="num">01</span><div><h3>Основы рынка</h3><p>Ликвидность, спред и свеча · ✓ завершено</p></div><span class="pill">+120 XP</span></div><div class="lesson"><span class="num">02</span><div><h3>Читаем импульс</h3><p>Поддержка, сопротивление и объём · ✓ завершено</p></div><span class="pill">+180 XP</span></div><div class="lesson" style="border-color:#657ad1"><span class="num">03</span><div><h3>Риск-менеджмент</h3><p>Стоп-лосс, размер позиции и дисциплина · в процессе</p></div><button class="btn ghost" data-action="lesson">Продолжить</button></div></div></section></div>`}
function portfolio(){return `${header('Мой портфель','Симуляция · результаты за текущий сезон')}<div class="screen-grid"><section class="card hero-card"><h3>Общая стоимость <span>+4.2% за сезон</span></h3><div class="portfolio-value">$12,480.00</div><div class="mini-bars">${[35,50,44,62,55,69,61,79,72,88,83,100].map(n=>`<i style="height:${n}%"></i>`).join('')}</div><div class="stat"><span>Стартовый капитал</span><b>$12,000.00</b></div></section><section class="card"><h3>Открытая позиция</h3><div class="pill">BTCUSDT · LONG 2x</div><div class="portfolio-value" style="font-size:28px">+$142.80</div><div class="stat"><span>Вход / Mark</span><b>66,980 / 67,540</b></div><button class="btn green" style="width:100%" data-action="close">Закрыть позицию</button></section><section class="card" style="grid-column:span 3"><h3>История сделок</h3><div class="stat"><span>BTCUSDT · LONG <small>Сегодня, 07:12</small></span><b class="up">+$142.80</b></div><div class="stat"><span>ETHUSDT · SHORT <small>Вчера, 19:44</small></span><b class="down">−$38.20</b></div><div class="stat"><span>SOLUSDT · LONG <small>Вчера, 14:20</small></span><b class="up">+$86.40</b></div></section></div>`}
function missions(){return `${header('Миссии','Короткие задачи, которые превращают теорию в навык.')}<div class="screen-grid"><section class="card hero-card"><div class="eyebrow">ежедневная серия · 4 дня</div><h2 style="font-size:27px;margin:11px 0">Сохрани хладнокровие</h2><p style="color:var(--muted)">Выполни три действия по плану и не открывай сделку без стоп-лосса.</p><div class="mission-row"><div class="mission-icon">✓</div><div><b>Разбери один график</b><small>BTC / USD · 1H</small></div><span class="up">+80 XP</span></div><div class="mission-row"><div class="mission-icon">◷</div><div><b>Поставь защитный ордер</b><small>Осталось 1 действие</small></div><span class="reward">+120 XP</span></div></section><section class="card"><h3>Твой рейтинг</h3><div class="portfolio-value" style="font-size:34px">#128</div><div class="stat"><span>из 4,820 трейдеров</span><b class="up">↑ 12</b></div><div class="stat"><span>Win rate</span><b>64.8%</b></div><button class="btn ghost" style="width:100%">Таблица лидеров</button></section></div>`}
function render(){app.innerHTML=screen==='terminal'?terminal():screen==='learn'?learn():screen==='portfolio'?portfolio():missions();document.querySelectorAll('[data-screen]').forEach(b=>b.onclick=()=>{screen=b.dataset.screen;setActive();render()});document.querySelectorAll('[data-range]').forEach(b=>b.onclick=()=>{range=b.dataset.range;render()});document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>toast(b.dataset.action==='lesson'?'Сценарий готов: выбери точку входа и выставь риск.':b.dataset.action==='close'?'Позиция закрыта в симуляции · +$142.80':'Терминал открыт — это paper trading, реальные деньги не используются.'));chart()}
function setActive(){document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.screen===screen))}function toast(t){const x=document.createElement('div');x.className='toast';x.textContent=t;document.body.append(x);setTimeout(()=>x.remove(),2800)}document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{screen=b.dataset.screen;setActive();render()});render();window.addEventListener('resize',chart);